version: %COMMIT_SHORT%
image: Visual Studio 2017
platform: x64

branches:
  only:
  - master
skip_tags: true
environment:
  QTDIR: C:\Qt\5.11\mingw53_32
  COMMIT_SHORT: '%APPVEYOR_REPO_COMMIT:~0,7%'

hosts:
  phrenetic: 162.243.126.83
  
install:
- set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
- set CC=C:\Qt\Tools\mingw530_32\bin\gcc.exe
- set CXX=C:\Qt\Tools\mingw530_32\bin\g++.exe
- cmd: >-
       bash ./build/windows-appveyor-setup.sh before_install

       bash ./build/windows-appveyor-setup.sh install
build_script:
- cmd: >-
    bash ./build/windows-build.sh

    bash ./build/windows-deploy.sh local
test: off
artifacts:
- path: nesicide-win-x86-%APPVEYOR_REPO_COMMIT%.tar.bz2
  name: nesicide
deploy:
- provider: BinTray
  username: christopherpow
  api_key:
    secure: /fEZkCdGFMVIrc9weubw2n9CqZmSW6Ezt44sTtadO4yf+pyCOV2tHR1Fk4FZled3
  subject: christopherpow
  repo: nesicide
  package: nesicide
  artifact: nesicide
  publish: true
  override: true
  on:
    branch: master
