os:
- linux
- osx
osx_image: xcode11.2
dist: xenial
language: cpp
before_install:
- travis_wait 60 ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install
install:
- travis_wait 60 ./build/${TRAVIS_OS_NAME}-travis-setup.sh install
script:
- travis_wait 60 ./build/${TRAVIS_OS_NAME}-build.sh
- travis_wait 60 ./build/${TRAVIS_OS_NAME}-deploy.sh local
addons:
  ssh_known_hosts: 162.243.126.83
before_deploy: 
- openssl aes-256-cbc -K $encrypted_c3ea658420f4_key -iv $encrypted_c3ea658420f4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  overwrite: true
  script: bash ./build/${TRAVIS_OS_NAME}-deploy.sh remote
  on:
    branch: master
    repo: christopherpow/nesicide
notifications:
  irc:
    channels:
    - chat.freenode.net#nesicide
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
